import type { TerminalTheme, TerminalThemeId } from "../../shared/types";

export const ONE_HALF_DARK: TerminalTheme = {
  colorScheme: "dark",
  background: "#282c34",
  foreground: "#dcdfe4",
  cursor: "#a3b8ef",
  cursorAccent: "#282c34",
  selectionBackground: "#474e5c",
  selectionForeground: "#dcdfe4",
  black: "#282c34",
  red: "#e06c75",
  green: "#98c379",
  yellow: "#e5c07b",
  blue: "#61afef",
  magenta: "#c678dd",
  cyan: "#56b6c2",
  white: "#dcdfe4",
  brightBlack: "#282c34",
  brightRed: "#e06c75",
  brightGreen: "#98c379",
  brightYellow: "#e5c07b",
  brightBlue: "#61afef",
  brightMagenta: "#c678dd",
  brightCyan: "#56b6c2",
  brightWhite: "#dcdfe4",
  searchHighlight: "#e5c07b",
};

export const ONE_HALF_LIGHT: TerminalTheme = {
  colorScheme: "light",
  background: "#fafafa",
  foreground: "#383c47",
  cursor: "#bfd7ff",
  cursorAccent: "#fafafa",
  selectionBackground: "#bfceea",
  selectionForeground: "#383c47",
  black: "#383c47",
  red: "#e45649",
  green: "#50a14f",
  yellow: "#c18401",
  blue: "#0184bc",
  magenta: "#a626a4",
  cyan: "#0997b3",
  white: "#fafafa",
  brightBlack: "#4f525d",
  brightRed: "#df6c75",
  brightGreen: "#98c379",
  brightYellow: "#e5c07b",
  brightBlue: "#61afef",
  brightMagenta: "#c678dd",
  brightCyan: "#56b6c2",
  brightWhite: "#ffffff",
  searchHighlight: "#c18401",
};

export const DRACULA: TerminalTheme = {
  colorScheme: "dark",
  background: "#282a36",
  foreground: "#f8f8f2",
  cursor: "#f8f8f2",
  cursorAccent: "#282a36",
  selectionBackground: "#44475a",
  selectionForeground: "#f8f8f2",
  black: "#21222c",
  red: "#ff5555",
  green: "#50fa7b",
  yellow: "#f1fa8c",
  blue: "#bd93f9",
  magenta: "#ff79c6",
  cyan: "#8be9fd",
  white: "#f8f8f2",
  brightBlack: "#6272a4",
  brightRed: "#ff6e6e",
  brightGreen: "#69ff94",
  brightYellow: "#ffffa5",
  brightBlue: "#d6acff",
  brightMagenta: "#ff92df",
  brightCyan: "#a4ffff",
  brightWhite: "#ffffff",
  searchHighlight: "#f1fa8c",
};

export const ALUCARD: TerminalTheme = {
  colorScheme: "light",
  background: "#fffbeb",
  foreground: "#1f1f1f",
  cursor: "#1f1f1f",
  cursorAccent: "#fffbeb",
  selectionBackground: "#cfcfde",
  selectionForeground: "#1f1f1f",
  black: "#fffbeb",
  red: "#cb3a2a",
  green: "#14710a",
  yellow: "#846e15",
  blue: "#644ac9",
  magenta: "#a3144d",
  cyan: "#036a96",
  white: "#1f1f1f",
  brightBlack: "#6c664b",
  brightRed: "#d74c3d",
  brightGreen: "#198d0c",
  brightYellow: "#9e841a",
  brightBlue: "#7862d0",
  brightMagenta: "#bf185a",
  brightCyan: "#047fb4",
  brightWhite: "#2c2b31",
  searchHighlight: "#846e15",
};

export const GITHUB_DARK: TerminalTheme = {
  colorScheme: "dark",
  background: "#0d1117",
  foreground: "#c9d1d9",
  cursor: "#c9d1d9",
  cursorAccent: "#0d1117",
  selectionBackground: "#1f6feb",
  selectionForeground: "#ffffff",
  black: "#484f58",
  red: "#ff7b72",
  green: "#3fb950",
  yellow: "#d29922",
  blue: "#58a6ff",
  magenta: "#bc8cff",
  cyan: "#39c5cf",
  white: "#b1bac4",
  brightBlack: "#6e7681",
  brightRed: "#ffa198",
  brightGreen: "#56d364",
  brightYellow: "#e3b341",
  brightBlue: "#79c0ff",
  brightMagenta: "#d2a8ff",
  brightCyan: "#56d4dd",
  brightWhite: "#f0f6fc",
  searchHighlight: "#d29922",
};

export const GITHUB_LIGHT: TerminalTheme = {
  colorScheme: "light",
  background: "#ffffff",
  foreground: "#24292f",
  cursor: "#24292f",
  cursorAccent: "#ffffff",
  selectionBackground: "#ddf4ff",
  selectionForeground: "#24292f",
  black: "#24292f",
  red: "#cf222e",
  green: "#116329",
  yellow: "#4d2d00",
  blue: "#0969da",
  magenta: "#8250df",
  cyan: "#1b7c83",
  white: "#6e7781",
  brightBlack: "#57606a",
  brightRed: "#a40e26",
  brightGreen: "#1a7f37",
  brightYellow: "#633c01",
  brightBlue: "#218bff",
  brightMagenta: "#a475f9",
  brightCyan: "#3192aa",
  brightWhite: "#8c959f",
  searchHighlight: "#d4a72c",
};

export const TERMINAL_THEMES: Record<TerminalThemeId, TerminalTheme> = {
  "one-half-dark": ONE_HALF_DARK,
  "one-half-light": ONE_HALF_LIGHT,
  dracula: DRACULA,
  alucard: ALUCARD,
  "github-dark": GITHUB_DARK,
  "github-light": GITHUB_LIGHT,
};

export const TERMINAL_THEME_OPTIONS: Array<{
  value: TerminalThemeId;
  label: string;
}> = [
  { value: "one-half-dark", label: "One Half Dark" },
  { value: "one-half-light", label: "One Half Light" },
  { value: "github-dark", label: "GitHub Dark" },
  { value: "github-light", label: "GitHub Light" },
  { value: "dracula", label: "Dracula" },
  { value: "alucard", label: "Alucard" },
];
